print("====parametric tests====")
options(help_type = "html")
library(RMySQL)
mm=dbConnect(dbDriver("MySQL"),"clg","rootuser","rootuser","127.0.0.1")
result=dbSendQuery(mm, "SELECT * FROM result where examination_id=5001")
ex_data_5001=dbFetch(result, n = -1)
rnum=as.numeric(ex_data_5001$result)
onlynum=rnum[!is.na(rnum)]
print(onlynum)
hist(onlynum[onlynum<1.5 & onlynum>0])
qqnorm(onlynum[onlynum<1.5 & onlynum>0])
qqline(onlynum[onlynum<1.5 & onlynum>0])
shapiro.test(onlynum[1:4999])
library(plotrix)
levels=seq(min(day2$Year),max(day2$Year),length.out=5)
clplot(day2$Year, day2$TP,ylab="Intake kC per day",xlab="year",levels, cols=c("green","red","green","orange","blue"),lty=1)
