#install.packages("sampler")
#install.packages("sampling")
help(sampling)
help(sampler)
help(srswr)
srswr(3,12)
help(srswor)
srswor(6,12)
#install.packages("samplingbook")
library(samplingbook)
help(samplingbook)
help(mtcars)
help(attach)
attach(mtcars)
mtcars
help(stratasamp)
View(mtcars)
vs1=mtcars[mtcars$vs==1,]
vs1
vs0=mtcars[mtcars$vs==0,]
vs0
total=nrow(mtcars)
nvs1=nrow(vs1)
nvs0=nrow(vs0)
sdvs0=sd(vs0$mpg)
sdvs1=sd(vs1$mpg)
ss=stratasamp(10,c(nrow(vs0),nrow(vs1)))
vs0s=vs0[sample(nrow(vs0),ss[2,1]),]
vs1s=vs1[sample(nrow(vs1),ss[2,2]),]
